package de.hsh.prog.gogodie.game.monster;

import de.hsh.prog.gogodie.game.gfx.AnimationID;

public enum MonsterAnimation implements AnimationID {

	NORMAL_MONSTER_WALK_UP,
	NORMAL_MONSTER_WALK_DOWN,
	NORMAL_MONSTER_WALK_LEFT,
	NORMAL_MONSTER_WALK_RIGHT,
	
	SPEED_MONSTER_WALK_UP,
	SPEED_MONSTER_WALK_DOWN,
	SPEED_MONSTER_WALK_LEFT,
	SPEED_MONSTER_WALK_RIGHT,
	
	SLOWLY_MONSTER_WALK_UP,
	SLOWLY_MONSTER_WALK_DOWN,
	SLOWLY_MONSTER_WALK_LEFT,
	SLOWLY_MONSTER_WALK_RIGHT,
	
	BOSS1_WALK_UP,
	BOSS1_WALK_DOWN,
	BOSS1_WALK_LEFT,
	BOSS1_WALK_RIGHT,
	
	BOSS2_WALK_UP,
	BOSS2_WALK_DOWN,
	BOSS2_WALK_LEFT,
	BOSS2_WALK_RIGHT
}
